<?php namespace Svz\GenericTest;

use PhpParser\ParserFactory;
use Svz\Generic\GenericPrinter;
use Symfony\Component\Filesystem\Filesystem;

class GenericPrinterTest extends \PHPUnit_Framework_TestCase
{
	protected function setUp()
	{

		$fs = new Filesystem();
		$fs->remove(__DIR__.'/tmp');
		parent::setUp(); // TODO: Change the autogenerated stub
	}


	public function testPrinter()
	{
		include_once __DIR__.'/SomeConcreteClass.php';
		include_once __DIR__.'/../SomeClass.php';

		$parser = (new ParserFactory)->create(ParserFactory::PREFER_PHP7);

		$ast = $parser->parse(file_get_contents(__DIR__ . '/../src/templates/GenericClass_Collection.php'));


		$p = new GenericPrinter(SomeInterface::class);
		$str = $p->prettyPrint($ast);
		$fs = new Filesystem();


		$fs->dumpFile(__DIR__.'/tmp/SomeConcreteClass_Collection.php','<?php '.$str);
		include_once __DIR__.'/tmp/SomeConcreteClass_Collection.php';

		/** @noinspection PhpUndefinedNamespaceInspection */
		$c = new SomeInterface\Collection();

		$items = [
			new SomeConcreteClass(1),
			new SomeConcreteClassExtension(2),
			new SomeConcreteClass(3),
			new SomeConcreteClass(4),
		//	new \SomeClass()
		];

		/** @var SomeConcreteClass $item */
		foreach ($items as $item){
			$c->add($item);
			$c->add(new SomeConcreteClass(4));
		}
		$c->get(3)->val;

		$c[1]->val;



	}

	protected function tearDown()
	{

		$fs = new Filesystem();
		$fs->remove(__DIR__.'/tmp');
		parent::tearDown();
	}
}
